[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "audio-transcriber"
version = "1.0.0"
description = "Audio Transcription App using faster-whisper"
requires-python = ">=3.11" 